[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B76A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2cb315fee8e754f2a4f6fed73c7ff4b8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B75AF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2cb315fee8e754f2a4f6fed73c7ff4b8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020E50B74E30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2cb315fee8e754f2a4f6fed73c7ff4b8